[project]
name = "splitpo"
version = "0.1.0"
description = "Splitting gettext .po files into smaller "
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
